# Default values for interlink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodeName: virtual-node

interlink:
  image: ghcr.io/intertwin-eu/interlink/virtual-kubelet-inttw:latest 
  enabled: false
  socket: null 
  # if socket is specified, the following fields are ignored
  address: http://localhost
  port: 4000

virtualNode:
  image: ghcr.io/intertwin-eu/interlink/interlink:latest 
  CPUs: 1000
  MemGiB: 1600
  Pods: 100
  HTTPProxies:
    HTTP: null
    HTTPs: null

plugin:
  enabled: false
  image: "" 
  commands: [] 
  args: []
  envs: []
  config: ""
  address: ""  
  port: 3000 
  socket: null

sshBastion:
  enabled: false
  image: lscr.io/linuxserver/openssh-server:latest 
  clientKeys:
    authorizedKey: ""
    keysURL: ""
  port: 31022
    
# if interlink.socket is specified, the following fields are ignored
OAUTH:
  image: ghcr.io/intertwin-eu/interlink/virtual-kubelet-inttw-refresh:latest
  TokenURL: DUMMY
  ClientID: DUMMY
  ClientSecret: DUMMY
  RefreshToken: DUMMY
  Audience: DUMMY

