# Default values for interlink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodeName: virtual-node

interlink:
  image: ghcr.io/intertwin-eu/interlink/virtual-kubelet-inttw:latest 
  name: default-vk
  enabled: false
  socket: null 
  # if socket is specified, the following fields are ignored
  address: http://localhost
  port: 4000

virtualNode:
  image: ghcr.io/intertwin-eu/interlink/virtual-kubelet-inttw:latest 
  name: default-vk
  CPUs: 1000
  MemGiB: 1600
  Pods: 100

plugin:
  address: ""  
  port: 3000 
  socket: null

ssh_bastion:
  clientKeys:
    priv: ""
    pub: ""
  port: 31022
    
# if interlink.socket is specified, the following fields are ignored
OAUTH:
  TokenURL: DUMMY
  ClientID: DUMMY
  ClientSecret: DUMMY
  RefreshToken: DUMMY
  Audience: DUMMY

