apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.nodeName }}-virtual-kubelet-config"
  namespace: {{ .Release.Namespace }}
data:
  InterLinkConfig.yaml: |
    InterlinkURL: "{{ if .Values.interlink.socket }}{{ .Values.interlink.socket }}{{ else }}{{ .Values.interlink.address }}{{ end }}"
    InterlinkPort: {{ if .Values.interlink.socket }}-1{{ else }}{{ .Values.interlink.port }}{{ end }}
    ExportPodData: true
    VerboseLogging: true
    ErrorsOnlyLogging: false
    ServiceAccount: "{{ .Values.nodeName }}"
    Namespace: "{{ .Release.Namespace }}"
    VKTokenFile: {{ if .Values.interlink.socket }}/dev/null{{ else }}/opt/interlink/token{{ end }}
    CPU: "{{ .Values.virtualNode.CPUs }}"
    Memory: "{{ .Values.virtualNode.MemGiB }}Gi"
    Pods: "{{ .Values.virtualNode.Pods }}"
    HTTP:
      Insecure: {{ .Values.virtualNode.HTTP.Insecure }}
    KubeletHTTP:
      Insecure: {{ .Values.virtualNode.KubeletHTTP.Insecure }}
---
{{- if .Values.interlink.socket }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.nodeName }}-interlink-config"
  namespace: {{ .Release.Namespace }}
data:
  InterLinkConfig.yaml: |
    InterlinkAddress: "{{ .Values.interlink.socket }}"
    SidecarURL: "{{ if .Values.plugin.socket }}{{ .Values.plugin.socket }}{{ else }}{{ .Values.plugin.address }}{{ end }}"
    SidecarPort: "{{ .Values.plugin.port }}"
    VerboseLogging: true
    ErrorsOnlyLogging: false
    ExportPodData: true
    DataRootFolder: "~/.interlink"
{{- end }}
---
{{- if .Values.plugin.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.nodeName }}-plugin-config"
  namespace: {{ .Release.Namespace }}
data:
  plugin.yaml: |
    {{ .Values.plugin.config | indent 4 }}
{{- end }}
