apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.nodeName }}-virtual-kubelet-config"
  namespace: {{ .Release.Namespace }}
data:
  InterLinkConfig.yaml: |
    {{- if .Values.interlink.socket }}
    InterlinkURL: {{ .Values.interlink.socket | quote }}
    InterlinkPort: {{ printf "%s-1" .Values.interlink.socket | quote }}
    {{- else }}
    InterlinkURL: {{ .Values.interlink.address | quote }}
    InterlinkPort: {{ .Values.interlink.port | quote }}
    {{- end }}
    ExportPodData: {{ .Values.interlink.exportPodData }}
    VerboseLogging: true
    ErrorsOnlyLogging: false
    ServiceAccount: "{{ .Values.nodeName }}"
    Namespace: "{{ .Release.Namespace }}"
    VKTokenFile: {{ .Values.OAUTH.enabled | ternary "/opt/interlink/token" "/dev/null" }}
    Resources:
      CPU: "{{ .Values.virtualNode.resources.CPUs }}"
      Memory: "{{ .Values.virtualNode.resources.memGib }}Gi"
      Pods: "{{ .Values.virtualNode.resources.pods }}"
      Accelerators:
      {{- range .Values.virtualNode.resources.accelerators }}
      - Resource_type: "{{ .resource_type }}"
        Model: "{{ .model }}"
        Available: {{ .available }}
      {{- end }}
    HTTP:
      Insecure: {{ .Values.virtualNode.HTTP.insecure }}
    KubeletHTTP:
      insecure: {{ .Values.virtualNode.kubeletHTTP.insecure }}
    NodeLabels:
      {{- range .Values.virtualNode.nodeLabels }}
      - "{{ . }}"
      {{- end }}
    NodeTaints:
      {{- range .Values.virtualNode.nodeTaints }}
      - key: "{{ .key }}"
        value: "{{ .value }}"
        effect: "{{ .effect }}"
      {{- end }}
---
{{- if .Values.interlink.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.nodeName }}-interlink-config"
  namespace: {{ .Release.Namespace }}
data:
  InterLinkConfig.yaml: |
    {{- if .Values.interlink.socket }}
    InterlinkAddress: {{ .Values.interlink.socket | quote }}
    {{- else }}
    InterlinkAddress: {{ .Values.interlink.address | quote }}
    InterlinkPort: {{ .Values.interlink.port | quote }}
    {{- end }}
    {{- if .Values.plugin.socket }}
    SidecarURL: {{ .Values.plugin.socket | quote }}
    {{- else }}
    SidecarURL: {{ .Values.plugin.address | quote }}
    SidecarPort: {{ .Values.plugin.port | quote }}
    {{- end }}
    VerboseLogging: true
    ErrorsOnlyLogging: false
    ExportPodData: {{ .Values.interlink.exportPodData }}
    DataRootFolder: /data/interlink
{{- end }}
---
{{- if .Values.plugin.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.nodeName }}-plugin-config"
  namespace: {{ .Release.Namespace }}
data:
  plugin.yaml: |
    {{ .Values.plugin.config | indent 4 }}
{{- end }}
